title: WYWYKE by MedPocket
description: "Medical Websites You Wish You Knew Earlier!"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://medpocket.github.io/WYWYKE"
favicon: favicon.ico
banner: https://raw.githubusercontent.com/MedPocket/.github/main/images/banner.jpg
twitter_username:
github_username: MedPocket
repository: https://github.com/AREA44/WYWYKE
google_analytics:
exclude: [readme.md]

sass:
  #style: compressed

# Build settings
markdown: kramdown

# Compress HTML
compress_html:
  clippings: all
  comments: []
  endings: [p, li, td]
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
